/**
 * Reference-based phoneme tuning script.
 *
 * 1. Reads WAV files generated by eSpeak (reference TTS)
 * 2. FFT-analyzes each to extract spectral envelope
 * 3. Maps energy to our 10 Voder bands
 * 4. Compares against our phoneme table
 * 5. Suggests gain adjustments
 *
 * Usage:
 *   espeak -v en -w /tmp/voder-ref/aa.wav -s 120 "[[A:]]"
 *   npx tsx scripts/tune-from-reference.ts
 */

import * as fs from 'fs'
import { BAND_CENTERS, BAND_WIDTHS, BAND_COMPENSATION, PHONEMES } from '../src/phonemes'

// ─── WAV reader (minimal, handles PCM 16-bit) ───

interface WavData {
  sampleRate: number
  samples: Float32Array
}

function readWav(path: string): WavData {
  const buf = fs.readFileSync(path)
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength)

  // Parse RIFF header
  const chunkSize = view.getUint32(4, true)
  let offset = 12 // skip RIFF header

  let sampleRate = 44100
  let bitsPerSample = 16
  let numChannels = 1
  let dataStart = 0
  let dataSize = 0

  while (offset < chunkSize + 8) {
    const id = String.fromCharCode(buf[offset], buf[offset + 1], buf[offset + 2], buf[offset + 3])
    const size = view.getUint32(offset + 4, true)
    if (id === 'fmt ') {
      numChannels = view.getUint16(offset + 10, true)
      sampleRate = view.getUint32(offset + 12, true)
      bitsPerSample = view.getUint16(offset + 22, true)
    } else if (id === 'data') {
      dataStart = offset + 8
      dataSize = size
    }
    offset += 8 + size
    if (size % 2 !== 0) offset++ // pad byte
  }

  const numSamples = dataSize / (bitsPerSample / 8) / numChannels
  const samples = new Float32Array(numSamples)
  for (let i = 0; i < numSamples; i++) {
    const byteOffset = dataStart + i * numChannels * (bitsPerSample / 8)
    if (bitsPerSample === 16) {
      samples[i] = view.getInt16(byteOffset, true) / 32768
    } else {
      samples[i] = (buf[byteOffset] - 128) / 128
    }
  }

  return { sampleRate, samples }
}

// ─── FFT (Cooley-Tukey radix-2) ───

function fft(real: Float64Array, imag: Float64Array): void {
  const n = real.length
  // Bit-reversal permutation
  for (let i = 1, j = 0; i < n; i++) {
    let bit = n >> 1
    while (j & bit) { j ^= bit; bit >>= 1 }
    j ^= bit
    if (i < j) {
      [real[i], real[j]] = [real[j], real[i]];
      [imag[i], imag[j]] = [imag[j], imag[i]]
    }
  }
  // Butterfly passes
  for (let len = 2; len <= n; len *= 2) {
    const halfLen = len / 2
    const angle = -2 * Math.PI / len
    const wR = Math.cos(angle)
    const wI = Math.sin(angle)
    for (let i = 0; i < n; i += len) {
      let curR = 1, curI = 0
      for (let j = 0; j < halfLen; j++) {
        const tR = curR * real[i + j + halfLen] - curI * imag[i + j + halfLen]
        const tI = curR * imag[i + j + halfLen] + curI * real[i + j + halfLen]
        real[i + j + halfLen] = real[i + j] - tR
        imag[i + j + halfLen] = imag[i + j] - tI
        real[i + j] += tR
        imag[i + j] += tI
        const newR = curR * wR - curI * wI
        curI = curR * wI + curI * wR
        curR = newR
      }
    }
  }
}

// ─── Spectral analysis ───

interface BandEnergy {
  center: number
  energy: number  // average magnitude in this band's frequency range
}

/**
 * Analyze a WAV file and return energy in each of our 10 bands.
 * Takes the middle 50% of the audio (skips onset/offset transients).
 */
function analyzeSpectrum(wav: WavData): BandEnergy[] {
  const { sampleRate, samples } = wav

  // Use the middle 50% to avoid onset/offset artifacts
  const start = Math.floor(samples.length * 0.25)
  const end = Math.floor(samples.length * 0.75)

  // FFT size — use 4096 for good frequency resolution
  const fftSize = 4096
  const numFrames = Math.floor((end - start) / fftSize)
  if (numFrames < 1) return BAND_CENTERS.map(c => ({ center: c, energy: 0 }))

  // Average spectrum across multiple frames
  const avgMag = new Float64Array(fftSize / 2)

  for (let frame = 0; frame < numFrames; frame++) {
    const offset = start + frame * fftSize
    const real = new Float64Array(fftSize)
    const imag = new Float64Array(fftSize)

    // Hann window
    for (let i = 0; i < fftSize; i++) {
      const w = 0.5 * (1 - Math.cos(2 * Math.PI * i / (fftSize - 1)))
      real[i] = (samples[offset + i] || 0) * w
    }

    fft(real, imag)

    for (let i = 0; i < fftSize / 2; i++) {
      avgMag[i] += Math.sqrt(real[i] * real[i] + imag[i] * imag[i]) / numFrames
    }
  }

  // Map FFT bins to our 10 bands
  const binHz = sampleRate / fftSize
  const bandEdges = [0, 225, 450, 700, 1000, 1400, 2000, 2700, 3800, 5400, 7500]

  return BAND_CENTERS.map((center, i) => {
    const loHz = bandEdges[i]
    const hiHz = bandEdges[i + 1]
    const loBin = Math.floor(loHz / binHz)
    const hiBin = Math.ceil(hiHz / binHz)

    let sum = 0
    let count = 0
    for (let bin = loBin; bin < hiBin && bin < avgMag.length; bin++) {
      sum += avgMag[bin]
      count++
    }
    return { center, energy: count > 0 ? sum / count : 0 }
  })
}

/**
 * Normalize band energies to 0-1 range (relative to peak).
 */
function normalize(bands: BandEnergy[]): number[] {
  const max = Math.max(...bands.map(b => b.energy), 0.001)
  return bands.map(b => b.energy / max)
}

// ─── Comparison ───

interface PhonemeComparison {
  phoneme: string
  refBands: number[]      // normalized reference (espeak)
  ourBands: number[]      // our compensated gains, normalized
  distance: number        // Euclidean distance
  suggestions: string[]   // per-band adjustment suggestions
  suggestedGains: number[] // proposed new gain values
}

function comparePhoneme(phoneme: string, refBands: number[]): PhonemeComparison {
  const ph = PHONEMES[phoneme]
  if (!ph) {
    return {
      phoneme, refBands, ourBands: Array(10).fill(0),
      distance: Infinity, suggestions: ['Phoneme not found'], suggestedGains: Array(10).fill(0)
    }
  }

  // Our compensated gains, normalized
  const ourRaw = ph.bands.map((g, i) => g * BAND_COMPENSATION[i])
  const ourMax = Math.max(...ourRaw, 0.001)
  const ourBands = ourRaw.map(g => g / ourMax)

  // Euclidean distance
  let sumSq = 0
  for (let i = 0; i < 10; i++) {
    sumSq += (refBands[i] - ourBands[i]) ** 2
  }
  const distance = Math.sqrt(sumSq)

  // Generate suggestions: where should we adjust?
  const suggestions: string[] = []
  const suggestedGains = [...ph.bands] // start from current

  for (let i = 0; i < 10; i++) {
    const diff = refBands[i] - ourBands[i]
    if (Math.abs(diff) > 0.15) {
      const direction = diff > 0 ? 'INCREASE' : 'DECREASE'
      const amount = Math.abs(diff)
      suggestions.push(`B${i + 1}(${BAND_CENTERS[i]}Hz): ${direction} by ${(amount * 100).toFixed(0)}% (ref=${refBands[i].toFixed(2)}, ours=${ourBands[i].toFixed(2)})`)

      // Compute suggested new gain: adjust proportionally
      // Account for band compensation in reverse
      const targetNormalized = refBands[i]
      const targetRaw = targetNormalized * ourMax / BAND_COMPENSATION[i]
      suggestedGains[i] = Math.max(0, Math.min(1.0, targetRaw))
    }
  }

  return { phoneme, refBands, ourBands, distance, suggestions, suggestedGains }
}

// ─── Main ───

const REF_DIR = process.env.REF_DIR || '/tmp/voder-ref-mac/vowels'

// Map our phonemes to espeak WAV filenames
const PHONEME_FILES: Record<string, string> = {
  AA: 'aa.wav',
  AE: 'ae.wav',
  AH: 'ah.wav',
  AO: 'ao.wav',
  EH: 'eh.wav',
  ER: 'er.wav',
  IH: 'ih.wav',
  IY: 'iy.wav',
  OW: 'ow.wav',
  UH: 'uh.wav',
  UW: 'uw.wav',
}

console.log('=== REFERENCE-BASED PHONEME TUNING ===')
console.log(`Reference TTS: eSpeak (${REF_DIR})`)
console.log()

const comparisons: PhonemeComparison[] = []

for (const [phoneme, filename] of Object.entries(PHONEME_FILES)) {
  const filepath = `${REF_DIR}/${filename}`
  if (!fs.existsSync(filepath)) {
    console.log(`  SKIP ${phoneme}: ${filepath} not found`)
    continue
  }

  const wav = readWav(filepath)
  const spectrum = analyzeSpectrum(wav)
  const refNorm = normalize(spectrum)
  const comparison = comparePhoneme(phoneme, refNorm)
  comparisons.push(comparison)

  const bar = (v: number) => '█'.repeat(Math.round(v * 20)).padEnd(20)
  console.log(`── ${phoneme} (distance: ${comparison.distance.toFixed(3)}) ──`)
  for (let i = 0; i < 10; i++) {
    const flag = Math.abs(refNorm[i] - comparison.ourBands[i]) > 0.15 ? ' ◄' : ''
    console.log(`  B${(i + 1).toString().padStart(2)}(${BAND_CENTERS[i].toString().padStart(4)}Hz)  ref=${bar(refNorm[i])} ${refNorm[i].toFixed(2)}  ours=${bar(comparison.ourBands[i])} ${comparison.ourBands[i].toFixed(2)}${flag}`)
  }
  if (comparison.suggestions.length) {
    console.log('  Suggestions:')
    for (const s of comparison.suggestions) console.log(`    ${s}`)
    console.log(`  Suggested gains: [${comparison.suggestedGains.map(g => g.toFixed(2)).join(', ')}]`)
  }
  console.log()
}

// Summary
console.log('=== SUMMARY ===')
comparisons.sort((a, b) => b.distance - a.distance)
for (const c of comparisons) {
  const status = c.distance < 0.3 ? '✓ GOOD' : c.distance < 0.5 ? '~ OK' : '✗ NEEDS WORK'
  console.log(`  ${c.phoneme.padEnd(4)} distance=${c.distance.toFixed(3)}  ${status}  ${c.suggestions.length} adjustments`)
}
console.log()

// Output suggested phoneme table update
console.log('=== SUGGESTED GAIN UPDATES ===')
console.log('(Copy these into phonemes.ts if the distance improves)')
for (const c of comparisons) {
  if (c.suggestions.length > 0) {
    console.log(`  ${c.phoneme}: bands: [${c.suggestedGains.map(g => g.toFixed(2)).join(', ')}]`)
  }
}
